version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE = data
      - MYSQL_USER= data
      - MYSQL_PASSWORD= data
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  eshop:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASES_DEFAULT_ENGINE: django.db.backends.mysql
      DATABASES_DEFAULT_NAME: data
      DATABASES_DEFAULT_USER: data
      DATABASES_DEFAULT_PASSWORD: data
      DATABASES_DEFAULT_HOST: mysql
      DATABASES_DEFAULT_PORT: 3306
    volumes:
      - .:/app
    links:
      - db:db
    networks:
      - my-network

networks:
  my-network:

volumes:
  db_data: