version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE = data
      - MYSQL_USER= data
      - MYSQL_PASSWORD= data
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  eshop:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3307
      - MYSQL_DATABASE=data
      - MYSQL_USER=root
    volumes:
      - .:/app
    links:
      - db:db

volumes:
  db_data:
  .:
