version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=data
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - .:/app

volumes:
  db_data:

