version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE : 'eshop_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - db_data/mysql/db:/var/lib/mysql
  eshop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: app:eShop
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - .:/eShop
