# Generated by Django 4.1.7 on 2023-02-19 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('TAN-TET-HOC', 'Tanger-Tétouan-Al Hoceïma'), ('ORI', "L'Oriental"), ('FE-MEK', 'Fès-Meknès'), ('RAB-SAL-KEN', 'Rabat-Salé-Kénitra'), ('BMEL-KHEN', 'Béni Mellal-Khénifra'), ('CASA-SET', 'Casablanca-Settat'), ('MAR-SAF', 'Marrakech-Safi'), ('DRA-TAF', 'Drâa-Tafilalet'), ('SOU-MAS', 'Souss-Massa'), ('GUE-ONOU', 'Guelmim-Oued Noun'), ('LAA-SAK', 'Laâyoune-Sakia El Hamra'), ('DAK-OED', 'Dakhla-Oued Ed-Dahab')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
