# Generated by Django 4.1.7 on 2023-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('content', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
